### ISSUE TITLE
grep not working, under macOs

### ISSUE THREAD

**Issue by mgiugliano** [connermcd/bin#1]
I would like to study and replicate your setup, especially the pdf2doi.

Something must be different with the regular expressions and with grep under macOs (despite bash), as I get a cryptic error when launching your pdf2doi:

```
-bash: ![\: event not found
```

Something must be wrong, despite you correctly escaped the symbol ", within the command

```
grep -oP "\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?![\"&\'<>])\S)+)\b"
```

Any suggestion from you would be precious!!

**Comment by connermcd** [comment]
The version of grep and it's associated flags are different on Mac; however, the problem here seems to be with bash. The exclamation point character (!) is special in bash when history expansion is enabled. My regex includes an ! and bash is trying to interpret that. See https://unix.stackexchange.com/questions/3747/understanding-the-exclamation-mark-in-bash

**Comment by mgiugliano** [comment]
Indeed macOs version of "grep" (BSD derived) is slightly different than GNU grep.
(see: https://apple.stackexchange.com/questions/275373/how-to-make-grep-work-like-in-ubuntu/275379) 

I have solved my problem, with pdf2doi function working correctly, by these two steps:

- installing GNU grep by 
```
brew install grep
```
note: the installed executable is called "ggrep"

- renaming the "grep" into "ggrep" within the pdf2doi.sh 

I hope it helps. Thank you @connermcd for your videos, repository, and for sharing your knowledge.
